// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopCore.Models;

namespace WorkshopCore.Migrations
{
    [DbContext(typeof(WorkshopContext))]
    [Migration("20180604234006_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkshopCore.Models.Request", b =>
                {
                    b.Property<Guid>("request_id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("request_id");

                    b.ToTable("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
